package com.damsky.danny.libremusic.data.db.model;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playlistDaoConfig;
    private final DaoConfig artistDaoConfig;
    private final DaoConfig albumDaoConfig;
    private final DaoConfig linkDaoConfig;
    private final DaoConfig genreDaoConfig;
    private final DaoConfig songDaoConfig;

    private final PlaylistDao playlistDao;
    private final ArtistDao artistDao;
    private final AlbumDao albumDao;
    private final LinkDao linkDao;
    private final GenreDao genreDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playlistDaoConfig = daoConfigMap.get(PlaylistDao.class).clone();
        playlistDaoConfig.initIdentityScope(type);

        artistDaoConfig = daoConfigMap.get(ArtistDao.class).clone();
        artistDaoConfig.initIdentityScope(type);

        albumDaoConfig = daoConfigMap.get(AlbumDao.class).clone();
        albumDaoConfig.initIdentityScope(type);

        linkDaoConfig = daoConfigMap.get(LinkDao.class).clone();
        linkDaoConfig.initIdentityScope(type);

        genreDaoConfig = daoConfigMap.get(GenreDao.class).clone();
        genreDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        playlistDao = new PlaylistDao(playlistDaoConfig, this);
        artistDao = new ArtistDao(artistDaoConfig, this);
        albumDao = new AlbumDao(albumDaoConfig, this);
        linkDao = new LinkDao(linkDaoConfig, this);
        genreDao = new GenreDao(genreDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(Playlist.class, playlistDao);
        registerDao(Artist.class, artistDao);
        registerDao(Album.class, albumDao);
        registerDao(Link.class, linkDao);
        registerDao(Genre.class, genreDao);
        registerDao(Song.class, songDao);
    }

    public void clear() {
        playlistDaoConfig.clearIdentityScope();
        artistDaoConfig.clearIdentityScope();
        albumDaoConfig.clearIdentityScope();
        linkDaoConfig.clearIdentityScope();
        genreDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public PlaylistDao getPlaylistDao() {
        return playlistDao;
    }

    public ArtistDao getArtistDao() {
        return artistDao;
    }

    public AlbumDao getAlbumDao() {
        return albumDao;
    }

    public LinkDao getLinkDao() {
        return linkDao;
    }

    public GenreDao getGenreDao() {
        return genreDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
